# Solution de l'exercice : manipulation d'un fichier CSV avec pandas

In [82]:
# import de la librairie pandas
import pandas as pd

## 1. Création d'un fichier CSV fictif (ventes.csv) à partir d'un DataFrame pandas

In [84]:
data = {
    "Date": ["2025-01-01", "2025-01-01", "2025-01-02", "2025-01-02", "2025-01-03"],
    "Vendeur": ["Jean", "Marie", "Jean", "Marie", "Paul"],
    "Produit": ["Ordinateur", "Souris", "Clavier", "Ordinateur", "Écran"],
    "Quantité": [3, 10, 5, 2, 4],
    "Prix_unitaire": [500, 20, 30, 500, 200]
}

df_initial = pd.DataFrame(data)
df_initial.to_csv("ventes.csv", index=False)

## 2. Lecture du fichier CSV avec pandas

In [87]:
def lire_csv(fichier):
    return pd.read_csv(fichier)

df = lire_csv("ventes.csv")

In [89]:
df

         Date Vendeur     Produit  Quantité  Prix_unitaire
0  2025-01-01    Jean  Ordinateur         3            500
1  2025-01-01   Marie      Souris        10             20
2  2025-01-02    Jean     Clavier         5             30
3  2025-01-02   Marie  Ordinateur         2            500
4  2025-01-03    Paul       Écran         4            200

## 3. Calcul du total des ventes

In [91]:
def calcul_total_ventes(df):
    df['Total'] = df['Quantité'] * df['Prix_unitaire']
    return df['Total'].sum()

total_ventes = calcul_total_ventes(df)
print("Total des ventes :", total_ventes)

Total des ventes : 3650

In [93]:
df

         Date Vendeur     Produit  Quantité  Prix_unitaire  Total
0  2025-01-01    Jean  Ordinateur         3            500   1500
1  2025-01-01   Marie      Souris        10             20    200
2  2025-01-02    Jean     Clavier         5             30    150
3  2025-01-02   Marie  Ordinateur         2            500   1000
4  2025-01-03    Paul       Écran         4            200    800

## 4. Quantité totale vendue par chaque vendeur

In [95]:
def quantite_par_vendeur(df):
    return df.groupby('Vendeur')['Quantité'].sum()

ventes_par_vendeur = quantite_par_vendeur(df)
print("Quantité totale vendue par vendeur :")
print(ventes_par_vendeur)

Quantité totale vendue par vendeur :
Vendeur
Jean      8
Marie    12
Paul      4
Name: Quantité, dtype: int64

## 5. Produit le plus vendu

In [99]:
def produit_plus_vendu(df):
    ventes_par_produit = df.groupby('Produit')['Quantité'].sum()
    print(ventes_par_produit)
    produit_max = ventes_par_produit.idxmax()
    quantite_max = ventes_par_produit.max()
    return produit_max, quantite_max

produit_max, quantite_max = produit_plus_vendu(df)
print(f"Produit le plus vendu : {produit_max} ({quantite_max} unités)")

Produit
Clavier        5
Ordinateur     5
Souris        10
Écran          4
Name: Quantité, dtype: int64
Produit le plus vendu : Souris (10 unités)

## 6. Journée avec le plus de revenus

In [101]:
def journee_plus_rentable(df):
    df['Total'] = df['Quantité'] * df['Prix_unitaire']
    revenus_par_jour = df.groupby('Date')['Total'].sum()
    print(revenus_par_jour)
    jour_max = revenus_par_jour.idxmax()
    revenus_max = revenus_par_jour.max()
    return jour_max, revenus_max

jour_max, revenus_max = journee_plus_rentable(df)
print(f"Journée avec le plus de revenus : {jour_max} (total : {revenus_max})")

Date
2025-01-01    1700
2025-01-02    1150
2025-01-03     800
Name: Total, dtype: int64
Journée avec le plus de revenus : 2025-01-01 (total : 1700)